server:
  port: 19001

security:
  basic:
    enabled: true
spring:
  datasource:
    username: root
    password: itstudio
    url: jdbc:mysql://120.25.193.26:3306/itmaoo_spider?useSSL=false&characterEncoding=utf-8&serverTimezone=UTC&useTimezone=true
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 20
  http:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  main:
    allow-bean-definition-overriding: true
mybatis:
  type-aliases-package: com.itmaoo.spider
  configuration:
    map-underscore-to-camel-case: true
management:
  endpoints:
    enabled-by-default: true
    web:
      base-path: /actuator
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
eureka: 
  client:
    register-with-eureka: false
    fetch-registry: false